### ISSUE TITLE
Reading FragPipe results

### ISSUE THREAD

**Issue by szabzola** [ftwkoopmans/msdap#33] opened 2024-07-24 13:16 UTC
Hi,
thanks again for the great, and continuosly improved tool.
If I want to reread an already analysed dataset using
dataset = import_dataset_fragpipe_ionquant("d:/DIR", acquisition_mode = "dda", collapse_peptide_by = "sequence_modified")
I got an error message in ver. 1.1 (did not chack older versions):
error: Cannot find "psm.tsv" file in FragPipe results at "d:/DIR/msdap_results"
When I run the script the first time, or I delete the results folder created by MSDAP, the analysis works.
It seems, that MSDAP searches for psm.tsv in EVERY subfolder of the working directory, instead of taking the list of psm files e.g. from "filelist_ionquant.txt" or sample (and dir) names from "experiment_annotation.tsv" or "fragpipe-files.fp-manifest", which are present in the Fragpipe output folder.

Another issue reading Fragpipe (FP) results: if I read the the fasta file used in fragpipe (which includes reverse sequences too), most of the protein groups in outputs are assigned to fasta headers like ">rev_sp|...", so I am not sure about appropriate assignments, combination of proteigroups to unique genes etc.
I can use original fasta without decoys, however contaminants AND reverse proteins are added in one step to fasta by FP, so contaminants may not be included in that, if I do not create it separately. 
(MSDAP userguide.md: "# this should be the same fasta file as provided in the FragPipe "Database" tab" however in example script the original fasta is given, without decoys, but that is also without contaminants)

Best regards,
Zoltan

**Comment by ftwkoopmans** [comment] 2024-07-29 13:25
> If I want to reread an already analysed dataset using
> dataset = import_dataset_fragpipe_ionquant("d:/DIR", acquisition_mode = "dda", collapse_peptide_by = "sequence_modified")
> I got an error message in ver. 1.1 (did not chack older versions):
> error: Cannot find "psm.tsv" file in FragPipe results at "d:/DIR/msdap_results"
> When I run the script the first time, or I delete the results folder created by MSDAP, the analysis works.
> It seems, that MSDAP searches for psm.tsv in EVERY subfolder of the working directory, instead of taking the list of psm files e.g. from "filelist_ionquant.txt" or sample (and dir) names from "experiment_annotation.tsv" or "fragpipe-files.fp-manifest", which are present in the Fragpipe output folder.

The problem is that the files that you mention (filelist_ionquant.txt / experiment_annotation.tsv / fragpipe-files.fp-manifest) may not always be present in FragPipe results, e.g. users may want to analyze data that was generated by FragPipe a few years ago and older versions provide different output files.

However, your comment is timely because we've been refactoring the FragPipe import function recently and this code will be included in the next MS-DAP update. In the meanwhile, I suggest to completely separate your input data (e.g. FragPipe/MaxQuant output directory) from the directory where you store output from other analyses/tools. For example, organize your files as `<project>/rawdata`, `<project>/fragpipe`, `<project>/code`, `<project>/msdap_output`, etc..


> Another issue reading Fragpipe (FP) results: if I read the the fasta file used in fragpipe (which includes reverse sequences too), most of the protein groups in outputs are assigned to fasta headers like ">rev_sp|...", so I am not sure about appropriate assignments, combination of proteigroups to unique genes etc.
> I can use original fasta without decoys, however contaminants AND reverse proteins are added in one step to fasta by FP, so contaminants may not be included in that, if I do not create it separately.

Good catch, this is a limitation/bug in MS-DAP. In the next MS-DAP release, decoy/reverse entries in the input FASTA will be correctly recognized and discarded so you can import the FragPipe-generated FASTA files that contain both the decoys and contaminant dataset

**Comment by ftwkoopmans** [comment] 2024-08-09 18:09
I've uploaded a new MS-DAP release with a major update to the Fragpipe import function and a bugfix for importing FASTA files that contain decoys from e.g. FragPipe.

Run the following code snippet to update the R package and only the minimum set of dependencies (you can replace upgrade="never" with upgrade="always" to update all dependencies if you want)

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```


For further details, see [release 1.1.1 changelog](https://github.com/ftwkoopmans/msdap/releases/tag/1.1.1) or check the respective function documentation after updating MS-DAP; `?import_dataset_fragpipe_ionquant`

**Closed as completed** 2024-09-04 15:47 UTC
