### ISSUE TITLE
Error in `stringr::str_split_fixed()`:

### ISSUE THREAD

**Issue by vcoyne1** [ftwkoopmans/msdap#15] opened 2023-07-10 09:00 UTC
Hi,

I am suddenly getting the following error message when running write_template_for_sample_metadata(dataset, "sample_metadata.xlsx")

Error in `stringr::str_split_fixed()`:
! `n` must be a whole number, not an integer `NA`.

I would be most grateful for any assistance with this as I have no idea how to fix this.

Thank you,
Vernon

**Comment by ftwkoopmans** [comment] 2023-07-10 17:19
thanks for the feedback, this seems to be a bug in MS-DAP.

Ideally, I'd use your dataset to reproduce this issue on my computer as this'll allow me to efficiently identify the cause, work on a fix and verify that it works for your data. Please upload your DIA-NN/Spectronaut/MaxQuant/x results somewhere as a ZIP file and email me a download link. You can find my email address as the corresponding author in the MS-DAP paper.

**Comment by vcoyne1** [comment] 2023-07-10 21:14
I've sent the data files as above. Looking forward to the fix.

**Comment by ftwkoopmans** [comment] 2023-07-18 16:17
Thanks for sharing the data and reporting this issue. The problem seems to be that your dataset contains only 1 sample/file; there's a bug in the current MS-DAP version that causes issues when creating the QC report if there is data for only 1 sample. A fix will be included in the next MS-DAP release, which is due later this summer.

Your dataset with 1 sample is s very uncommon use-case for MS-DAP, which is why we won't move our next scheduled update forward to issue an immediate fix/update for this issue (that seems to only affects datasets with 1 sample). After all, the up-shot for MS-DAP is to perform filtering/normalization/statistics and plot QC figures for label-free proteomics datasets and this requires datasets with multiple samples. Example use-cases for MS-DAP range from small datasets that e.g. compare 3 replicates of controls versus 3 replicates of some mutant/phenotype, to large datasets that e.g. aim to compare across multiple experimental conditions (with potentially many biological replicates for each respective condition).

Since your dataset contains only 1 sample, I suggest you can directly work with the DIA-NN result files (e.g. the proteingroup result table that is typically named something like "report.pg_matrix.tsv"). If you encounter additional issues with MS-DAP on datasets that consist of multiple samples, feel free to open a new issue / GitHub ticket.

**Closed as completed by ftwkoopmans** 2023-07-18 16:17 UTC
