### ISSUE TITLE
Failure to generate QC report 

### ISSUE THREAD

**Issue by biancacotto** [ftwkoopmans/msdap#29] opened 2024-06-12 20:03 UTC
Hello! Thanks for creating such an awesome package! This has been a total game changer for me. 

Recently I have been running to an issue where the QC report fails to generate (this was not happening before).

This is the error message 

sh: line 1: 165461 Segmentation fault      (core dumped) 'xelatex' -halt-on-error -interaction=batchmode 'report.tex' > /dev/null 2> '/tmp/Rtmp6q3WSx/stderr164bf7d92f097'
! xdvipdfmx:fatal: File ended prematurely

! No output PDF file written.

I have done a lot of google searching and have no clue how to resolve. It seems like in the temporary folder the reports_files folder is being deleted before the pdf finishes compiling and this is causing the failure. This is my best guess.

Below is the last line in the report.log. 

<img width="943" alt="Screenshot 2024-06-12 at 4 03 26 PM" src="https://github.com/ftwkoopmans/msdap/assets/144383593/26d9b623-5d5b-435a-b7bc-58ebbb3d569d">

Any suggestions?

**Comment by ftwkoopmans** [comment] 2024-06-13 09:45
Such errors are quite difficult to debug as I cannot reproduce the problem on my computer. If MS-DAP is entirely broken on your system, i.e. you get these errors with every dataset, perhaps there are issues with your latex/tinytex installation or perhaps you recently updated some R package (ggplot2?!) which ultimately causes the error you see at the end of this log. 



1) First thing to try is to ensure you have the latest MS-DAP version. For example, a recent ggplot2 release caused problems with MS-DAP so if you recently updated ggplot2 this could be the underlying issue; this was fixed in an MS-DAP update. Restart RStudio so you have a clean R session, then execute this to update MS-DAP:
```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```



2) If the issue persists, try to update your tinytex installation.
```
install.packages("tinytex")
```
restart RStudio
```
tinytex::uninstall_tinytex()
tinytex::install_tinytex()
```
restart RStudio again and try to re-run your MS-DAP report.



3) If prior steps did not resolve the issue;

A) please share your operating system, R version, MS-DAP package version, etc. by executing the following R code (in a new R session) and copy/pasting the output.
```
library(msdap)
devtools::session_info()
```
B) also include the full output log instead of the small snippet you shared previously so I can check for upstream errors (you can share it by email as well, my email address is listed as corresponding author in the MS-DAP manuscript)

**Comment by ftwkoopmans** [comment] 2024-06-17 17:58
After some back and forth by email it seems that this is a MacOS specific issue (i.e. same dataset, same R code works on Windows). The root issue is hard to pinpoint, but @biancacotto did find a workaround:

>  if I keep the temporary folder (in the MS-DAP output directory) open while the report is being generated then I do not receive the error and I am able to get the report

I'll close the ticket for now as I suspect/hope this is a very rare issue. If other users encounter similar errors as the opening post, please post your full console log (including stuff prior to the actual error message) and post information about your computer and installed R packages using this R snippet; `library(msdap); devtools::session_info()`. Further, please check whether you run into any issues if you don't perform DEA (i.e. don't use `setup_contrasts()` )

**Closed as completed by ftwkoopmans** 2024-06-17 17:58 UTC
